In [3]:
#install and import necessary packages
!pip install flask-ngrok
import tensorflow as tf
import cv2 as cv
import flask
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from keras.preprocessing import image
from tensorflow.keras.preprocessing import image
import os
from flask_ngrok import run_with_ngrok
from flask import Flask, render_template, request 

#Load the model
model = tf.keras.models.load_model('/content/drive/MyDrive/webapp/model/cov_pre_mod.h5') 


app = flask.Flask(__name__, template_folder='/content/drive/My Drive/webapp/templates')
run_with_ngrok(app) 

app.config['UPLOAD_FOLDER'] = '/content/drive/My Drive/webapp/uploaded/image'
@app.route('/', methods=['GET', 'POST'])
def main():
    if flask.request.method == 'GET':
        return(flask.render_template('main.html'))

    if flask.request.method == 'POST':
        images1 = []

        vals = ['COVID-19', 'NORMAL', 'VIRAL PNEUMONIA']

        image_size = 256
        input_variables = flask.request.files['avatar']
        print(input_variables.filename)
        FN = input_variables.filename
        input_variables.save(os.path.join(app.config['UPLOAD_FOLDER'], FN))
   
        IMA = os.path.join('/content/drive/My Drive/webapp/uploaded/image/', FN)

        image1_read = cv.imread(IMA, 0)
        image1_resized = cv.resize(image1_read,(image_size ,image_size),cv.IMREAD_GRAYSCALE)/255.0
        images1.append(image1_resized)
        images1 = np.array(images1)
        images1 = np.expand_dims(images1, axis = 3)

        prediction = model.predict(images1)
        print(prediction) 
        r = str(vals[np.argmax(prediction)])

        print(r)
        
        return flask.render_template('pred.html', ss=r)

if __name__ == '__main__':
    app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://16a261201db5.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


127.0.0.1 - - [17/Nov/2020 22:01:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 22:01:36] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Nov/2020 22:01:47] "POST / HTTP/1.1" 200 -


Covid3.png
[[9.9999166e-01 5.7050380e-07 7.7561554e-06]]
COVID-19


127.0.0.1 - - [17/Nov/2020 22:01:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 22:02:19] "POST / HTTP/1.1" 200 -


Normal1.png
[[1.06325695e-08 9.99989033e-01 1.10085202e-05]]
NORMAL


127.0.0.1 - - [17/Nov/2020 22:02:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 22:05:06] "POST / HTTP/1.1" 200 -


Normal2.png
[[1.9006420e-08 9.9998379e-01 1.6264876e-05]]
NORMAL


127.0.0.1 - - [17/Nov/2020 22:06:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 22:06:52] "POST / HTTP/1.1" 200 -


Normal3.png
[[2.9255622e-08 9.9997771e-01 2.2297414e-05]]
NORMAL


127.0.0.1 - - [17/Nov/2020 22:07:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 22:07:33] "POST / HTTP/1.1" 200 -


Viral_Pneumonia1.png
[[4.962249e-04 8.512306e-04 9.986525e-01]]
VIRAL PNEUMONIA


127.0.0.1 - - [17/Nov/2020 22:07:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 22:08:10] "POST / HTTP/1.1" 200 -


Viral_Pneumonia2.png
[[4.0321588e-04 9.4079564e-04 9.9865592e-01]]
VIRAL PNEUMONIA


127.0.0.1 - - [17/Nov/2020 22:08:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 22:08:59] "POST / HTTP/1.1" 200 -


Viral_Pneumonia3.png
[[4.6263912e-04 8.9078699e-04 9.9864656e-01]]
VIRAL PNEUMONIA


127.0.0.1 - - [17/Nov/2020 22:09:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 22:09:28] "POST / HTTP/1.1" 200 -


Viral_Pneumonia4.png
[[7.7492691e-04 8.6903811e-04 9.9835604e-01]]
VIRAL PNEUMONIA
